;Board information
;ALL FIELDS SHOULD BE LESS THAN 25 CHAR
[Board]
	;NEEDS TO BE SET IN "CONFIG.H" PRIOR TO FLASHING TO TEENSY & NANO
	;Select one of the available board names (see list in Config.h)
	;Define the board version in "BOARD_VERSION" slot immedietly after the list

[Exo]
	name = test
    
[Battery]
    ;Describes the type of battery used, values: smart(inspired energy), dumb (simple lipo)
	name = dumb

[test]     ; [bilateralHipAnkle]
	;Sides - left, right, bilateral	
	sides = bilateral

	;Joints used and their motor name, 0 = not useed, AK60, AK60v1.1, AK70, are AK80 the different CAN motors.
    	;Values 0(not used), AK60, AK60v1.1, AK70, AK80, MaxonMotor
	knee = 0
	ankle = 0
    
    	;Joint gear ratio = velocity of driving member (motor)/velocity of the driven member (output shaft), assumes constant gearing ratio. If the motor spins 6 revolutions to 1 revolution of the output this value would be 6.
    	;This is for transmission gearing after the motor output shaft. If the Motor has a built in gearing that should be part of the motor class (see motor.h/.cpp)
    	;Values 1, 2, 3, 4.5

	kneeGearRatio = 1
	ankleGearRatio = 4.5


	;Default controller for the joint
	;Knee Controllers: zeroTorque, constantTorque, chirp, step
	;Ankle Controllers: zeroTorque, PJMC, zhangCollins, constantTorque, TREC, calibrManager, chirp, step, SPV2, PJMC_PLUS 

	kneeDefaultController = 0
	ankleDefaultController = 0
    
    ;Do you want to use a torque sensor for these joints, 0 = no, yes = yes

	kneeUseLoadcell = 0
	ankleUseLoadcell = 0

	;Do you want to use a torque sensor for these joints, 0 = no, yes = yes

	kneeUseIMU = 0
	ankleUseIMU = 0


 

